# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build thorsten-kasel-backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # if you add permissions here this needs to be done in the thorsten-kasel-backend-orchestration.yaml as well
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Render templates
        uses: ionos-deploy-now/template-renderer-action@v2
        id: template
        with:
          input-directory: .deploy-now/thorsten-kasel-backend
          output-directory: ${{ env.DEPLOYMENT_FOLDER }}
          intermediate-data-file: ${{ env.DEPLOYMENT_FOLDER }}/.template-renderer-data

      - name: Setup composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:2

      - name: Run composer update
        env:
          ADMIN_PASSWORD: test1234
          APP_DEBUG: true
          APP_ENV: production
          APP_FAKER_LOCALE: en_US
          APP_FALLBACK_LOCALE: en
          APP_KEY: base64:zygcwt+CGjQcJMyM/QEJ5XtxDYs8+WDtMAZe8owR4j0=
          APP_LOCALE: de
          APP_MAINTENANCE_DRIVER: file
          APP_NAME: Laravel
          AWS_ACCESS_KEY_ID: AKIA4UBBK4DWG7SP6HUZ
          AWS_BUCKET: kasel-images
          AWS_DEFAULT_REGION: eu-central-1
          AWS_SECRET_ACCESS_KEY: 2d8w02ZZjDnhhSK3usvg2U77g8oKwHLNeXts8enw
          AWS_USE_PATH_STYLE_ENDPOINT: false
          BCRYPT_ROUNDS: 12
          BROADCAST_CONNECTION: null
          CACHE_STORE: database
          CORS_ALLOWED_ORIGINS: https://home-5019501087.app-ionos.space
          DB_CONNECTION: mysql
          DB_PORT: 3306
          FILESYSTEM_DISK: local
          FRONTEND_KEY: https://home-5019501087.app-ionos.space
          LOG_CHANNEL: stack
          LOG_DEPRECATIONS_CHANNEL: null
          LOG_LEVEL: debug
          LOG_STACK: single
          MEMCACHED_HOST: 127.0.0.1
          PHP_CLI_SERVER_WORKERS: 4
          QUEUE_CONNECTION: database
          RECAPTCHA_SECRET_KEY: 6Lcpy0wsAAAAAMcpX_4haiCuZjRvB7UXkWHkuDt7
          RECAPTCHA_SITE_KEY: 6Lcpy0wsAAAAAHxURCD3v8uNQpk7ZTovpir9bqx0
          REDIS_CLIENT: phpredis
          REDIS_HOST: 127.0.0.1
          REDIS_PASSWORD: null
          REDIS_PORT: 6379
          SESSION_DOMAIN: null
          SESSION_DRIVER: database
          SESSION_ENCRYPT: false
          SESSION_LIFETIME: 120
          SESSION_PATH: /
          VITE_APP_NAME: "${APP_NAME}"
        run: composer update --optimize-autoloader

      - name: Run composer install
        env:
          ADMIN_PASSWORD: test1234
          APP_DEBUG: true
          APP_ENV: production
          APP_FAKER_LOCALE: en_US
          APP_FALLBACK_LOCALE: en
          APP_KEY: base64:zygcwt+CGjQcJMyM/QEJ5XtxDYs8+WDtMAZe8owR4j0=
          APP_LOCALE: de
          APP_MAINTENANCE_DRIVER: file
          APP_NAME: Laravel
          AWS_ACCESS_KEY_ID: AKIA4UBBK4DWG7SP6HUZ
          AWS_BUCKET: kasel-images
          AWS_DEFAULT_REGION: eu-central-1
          AWS_SECRET_ACCESS_KEY: 2d8w02ZZjDnhhSK3usvg2U77g8oKwHLNeXts8enw
          AWS_USE_PATH_STYLE_ENDPOINT: false
          BCRYPT_ROUNDS: 12
          BROADCAST_CONNECTION: null
          CACHE_STORE: database
          CORS_ALLOWED_ORIGINS: https://home-5019501087.app-ionos.space
          DB_CONNECTION: mysql
          DB_PORT: 3306
          FILESYSTEM_DISK: local
          FRONTEND_KEY: https://home-5019501087.app-ionos.space
          LOG_CHANNEL: stack
          LOG_DEPRECATIONS_CHANNEL: null
          LOG_LEVEL: debug
          LOG_STACK: single
          MEMCACHED_HOST: 127.0.0.1
          PHP_CLI_SERVER_WORKERS: 4
          QUEUE_CONNECTION: database
          RECAPTCHA_SECRET_KEY: 6Lcpy0wsAAAAAMcpX_4haiCuZjRvB7UXkWHkuDt7
          RECAPTCHA_SITE_KEY: 6Lcpy0wsAAAAAHxURCD3v8uNQpk7ZTovpir9bqx0
          REDIS_CLIENT: phpredis
          REDIS_HOST: 127.0.0.1
          REDIS_PASSWORD: null
          REDIS_PORT: 6379
          SESSION_DOMAIN: null
          SESSION_DRIVER: database
          SESSION_ENCRYPT: false
          SESSION_LIFETIME: 120
          SESSION_PATH: /
          VITE_APP_NAME: "${APP_NAME}"
        run: composer install --optimize-autoloader

      - name: Build PHP assets
        env:
          ADMIN_PASSWORD: test1234
          APP_DEBUG: true
          APP_ENV: production
          APP_FAKER_LOCALE: en_US
          APP_FALLBACK_LOCALE: en
          APP_KEY: base64:zygcwt+CGjQcJMyM/QEJ5XtxDYs8+WDtMAZe8owR4j0=
          APP_LOCALE: de
          APP_MAINTENANCE_DRIVER: file
          APP_NAME: Laravel
          AWS_ACCESS_KEY_ID: AKIA4UBBK4DWG7SP6HUZ
          AWS_BUCKET: kasel-images
          AWS_DEFAULT_REGION: eu-central-1
          AWS_SECRET_ACCESS_KEY: 2d8w02ZZjDnhhSK3usvg2U77g8oKwHLNeXts8enw
          AWS_USE_PATH_STYLE_ENDPOINT: false
          BCRYPT_ROUNDS: 12
          BROADCAST_CONNECTION: null
          CACHE_STORE: database
          CORS_ALLOWED_ORIGINS: https://home-5019501087.app-ionos.space
          DB_CONNECTION: mysql
          DB_PORT: 3306
          FILESYSTEM_DISK: local
          FRONTEND_KEY: https://home-5019501087.app-ionos.space
          LOG_CHANNEL: stack
          LOG_DEPRECATIONS_CHANNEL: null
          LOG_LEVEL: debug
          LOG_STACK: single
          MEMCACHED_HOST: 127.0.0.1
          PHP_CLI_SERVER_WORKERS: 4
          QUEUE_CONNECTION: database
          RECAPTCHA_SECRET_KEY: 6Lcpy0wsAAAAAMcpX_4haiCuZjRvB7UXkWHkuDt7
          RECAPTCHA_SITE_KEY: 6Lcpy0wsAAAAAHxURCD3v8uNQpk7ZTovpir9bqx0
          REDIS_CLIENT: phpredis
          REDIS_HOST: 127.0.0.1
          REDIS_PASSWORD: null
          REDIS_PORT: 6379
          SESSION_DOMAIN: null
          SESSION_DRIVER: database
          SESSION_ENCRYPT: false
          SESSION_LIFETIME: 120
          SESSION_PATH: /
          VITE_APP_NAME: "${APP_NAME}"
        run: php artisan key:generate --force -n

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v22.x

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 691b3412-bbdc-4c0c-a703-bfa66979128a
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/thorsten-kasel-backend/config.yaml
          action: upload
